# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /DATA_2/Programmation/C/RBR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /DATA_2/Programmation/C/RBR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /DATA_2/Programmation/C/RBR/CMakeFiles /DATA_2/Programmation/C/RBR//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /DATA_2/Programmation/C/RBR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TankStorm

# Build rule for target.
TankStorm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TankStorm
.PHONY : TankStorm

# fast build rule for target.
TankStorm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/build
.PHONY : TankStorm/fast

src/button.o: src/button.cpp.o
.PHONY : src/button.o

# target to build an object file
src/button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/button.cpp.o
.PHONY : src/button.cpp.o

src/button.i: src/button.cpp.i
.PHONY : src/button.i

# target to preprocess a source file
src/button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/button.cpp.i
.PHONY : src/button.cpp.i

src/button.s: src/button.cpp.s
.PHONY : src/button.s

# target to generate assembly for a file
src/button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/button.cpp.s
.PHONY : src/button.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/input_manager.o: src/input_manager.cpp.o
.PHONY : src/input_manager.o

# target to build an object file
src/input_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/input_manager.cpp.o
.PHONY : src/input_manager.cpp.o

src/input_manager.i: src/input_manager.cpp.i
.PHONY : src/input_manager.i

# target to preprocess a source file
src/input_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/input_manager.cpp.i
.PHONY : src/input_manager.cpp.i

src/input_manager.s: src/input_manager.cpp.s
.PHONY : src/input_manager.s

# target to generate assembly for a file
src/input_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/input_manager.cpp.s
.PHONY : src/input_manager.cpp.s

src/keyboard_player.o: src/keyboard_player.cpp.o
.PHONY : src/keyboard_player.o

# target to build an object file
src/keyboard_player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/keyboard_player.cpp.o
.PHONY : src/keyboard_player.cpp.o

src/keyboard_player.i: src/keyboard_player.cpp.i
.PHONY : src/keyboard_player.i

# target to preprocess a source file
src/keyboard_player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/keyboard_player.cpp.i
.PHONY : src/keyboard_player.cpp.i

src/keyboard_player.s: src/keyboard_player.cpp.s
.PHONY : src/keyboard_player.s

# target to generate assembly for a file
src/keyboard_player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/keyboard_player.cpp.s
.PHONY : src/keyboard_player.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/menu.o: src/menu.cpp.o
.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i
.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s
.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

src/missile.o: src/missile.cpp.o
.PHONY : src/missile.o

# target to build an object file
src/missile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/missile.cpp.o
.PHONY : src/missile.cpp.o

src/missile.i: src/missile.cpp.i
.PHONY : src/missile.i

# target to preprocess a source file
src/missile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/missile.cpp.i
.PHONY : src/missile.cpp.i

src/missile.s: src/missile.cpp.s
.PHONY : src/missile.s

# target to generate assembly for a file
src/missile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/missile.cpp.s
.PHONY : src/missile.cpp.s

src/play.o: src/play.cpp.o
.PHONY : src/play.o

# target to build an object file
src/play.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/play.cpp.o
.PHONY : src/play.cpp.o

src/play.i: src/play.cpp.i
.PHONY : src/play.i

# target to preprocess a source file
src/play.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/play.cpp.i
.PHONY : src/play.cpp.i

src/play.s: src/play.cpp.s
.PHONY : src/play.s

# target to generate assembly for a file
src/play.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/play.cpp.s
.PHONY : src/play.cpp.s

src/settings.o: src/settings.cpp.o
.PHONY : src/settings.o

# target to build an object file
src/settings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/settings.cpp.o
.PHONY : src/settings.cpp.o

src/settings.i: src/settings.cpp.i
.PHONY : src/settings.i

# target to preprocess a source file
src/settings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/settings.cpp.i
.PHONY : src/settings.cpp.i

src/settings.s: src/settings.cpp.s
.PHONY : src/settings.s

# target to generate assembly for a file
src/settings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/settings.cpp.s
.PHONY : src/settings.cpp.s

src/tank.o: src/tank.cpp.o
.PHONY : src/tank.o

# target to build an object file
src/tank.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/tank.cpp.o
.PHONY : src/tank.cpp.o

src/tank.i: src/tank.cpp.i
.PHONY : src/tank.i

# target to preprocess a source file
src/tank.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/tank.cpp.i
.PHONY : src/tank.cpp.i

src/tank.s: src/tank.cpp.s
.PHONY : src/tank.s

# target to generate assembly for a file
src/tank.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/tank.cpp.s
.PHONY : src/tank.cpp.s

src/terrain.o: src/terrain.cpp.o
.PHONY : src/terrain.o

# target to build an object file
src/terrain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/terrain.cpp.o
.PHONY : src/terrain.cpp.o

src/terrain.i: src/terrain.cpp.i
.PHONY : src/terrain.i

# target to preprocess a source file
src/terrain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/terrain.cpp.i
.PHONY : src/terrain.cpp.i

src/terrain.s: src/terrain.cpp.s
.PHONY : src/terrain.s

# target to generate assembly for a file
src/terrain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/terrain.cpp.s
.PHONY : src/terrain.cpp.s

src/tool.o: src/tool.cpp.o
.PHONY : src/tool.o

# target to build an object file
src/tool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/tool.cpp.o
.PHONY : src/tool.cpp.o

src/tool.i: src/tool.cpp.i
.PHONY : src/tool.i

# target to preprocess a source file
src/tool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/tool.cpp.i
.PHONY : src/tool.cpp.i

src/tool.s: src/tool.cpp.s
.PHONY : src/tool.s

# target to generate assembly for a file
src/tool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TankStorm.dir/build.make CMakeFiles/TankStorm.dir/src/tool.cpp.s
.PHONY : src/tool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TankStorm"
	@echo "... src/button.o"
	@echo "... src/button.i"
	@echo "... src/button.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/input_manager.o"
	@echo "... src/input_manager.i"
	@echo "... src/input_manager.s"
	@echo "... src/keyboard_player.o"
	@echo "... src/keyboard_player.i"
	@echo "... src/keyboard_player.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
	@echo "... src/missile.o"
	@echo "... src/missile.i"
	@echo "... src/missile.s"
	@echo "... src/play.o"
	@echo "... src/play.i"
	@echo "... src/play.s"
	@echo "... src/settings.o"
	@echo "... src/settings.i"
	@echo "... src/settings.s"
	@echo "... src/tank.o"
	@echo "... src/tank.i"
	@echo "... src/tank.s"
	@echo "... src/terrain.o"
	@echo "... src/terrain.i"
	@echo "... src/terrain.s"
	@echo "... src/tool.o"
	@echo "... src/tool.i"
	@echo "... src/tool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

